/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSectionIdIndexRouteImport } from './routes/learn/$sectionId/index'
import { Route as LearnSectionIdLessonIdRouteImport } from './routes/learn/$sectionId/$lessonId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSectionIdIndexRoute = LearnSectionIdIndexRouteImport.update({
  id: '/learn/$sectionId/',
  path: '/learn/$sectionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSectionIdLessonIdRoute = LearnSectionIdLessonIdRouteImport.update({
  id: '/learn/$sectionId/$lessonId',
  path: '/learn/$sectionId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/profile': typeof ProfileRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$sectionId/$lessonId': typeof LearnSectionIdLessonIdRoute
  '/learn/$sectionId/': typeof LearnSectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/profile': typeof ProfileRoute
  '/learn': typeof LearnIndexRoute
  '/learn/$sectionId/$lessonId': typeof LearnSectionIdLessonIdRoute
  '/learn/$sectionId': typeof LearnSectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/profile': typeof ProfileRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$sectionId/$lessonId': typeof LearnSectionIdLessonIdRoute
  '/learn/$sectionId/': typeof LearnSectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/profile'
    | '/learn/'
    | '/learn/$sectionId/$lessonId'
    | '/learn/$sectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/profile'
    | '/learn'
    | '/learn/$sectionId/$lessonId'
    | '/learn/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/profile'
    | '/learn/'
    | '/learn/$sectionId/$lessonId'
    | '/learn/$sectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  ProfileRoute: typeof ProfileRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnSectionIdLessonIdRoute: typeof LearnSectionIdLessonIdRoute
  LearnSectionIdIndexRoute: typeof LearnSectionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$sectionId/': {
      id: '/learn/$sectionId/'
      path: '/learn/$sectionId'
      fullPath: '/learn/$sectionId/'
      preLoaderRoute: typeof LearnSectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$sectionId/$lessonId': {
      id: '/learn/$sectionId/$lessonId'
      path: '/learn/$sectionId/$lessonId'
      fullPath: '/learn/$sectionId/$lessonId'
      preLoaderRoute: typeof LearnSectionIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  ProfileRoute: ProfileRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnSectionIdLessonIdRoute: LearnSectionIdLessonIdRoute,
  LearnSectionIdIndexRoute: LearnSectionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
